### ISSUE TITLE
fail to set VREG_W=2048

### ISSUE THREAD

**Issue by schwa1z** [vproc/vicuna#106]
Hi, @michael-platzer @stevobailey @moimfeld 
As vicuna user guide shows, the VREG_W could be set with 64/512/2048.
![image](https://user-images.githubusercontent.com/65495072/193442684-a8f53631-abdc-4b4a-b51d-14462c13a911.png)
While when I use the following command to configure vicuna:
 ```
make -f /home/mango/my-vicuna/sim/Makefile CORE=cv32e40x PROG_PATHS=progs.txt VPROC_CONFIG=triple VREG_W=2048
```
error occured:
![image](https://user-images.githubusercontent.com/65495072/193442757-d4a240f8-0920-4168-90ee-689c13a29676.png)
When I set VREG_W<=1024, no error occurs. So what's the problem?
Thanks!

**Comment by michael-platzer** [comment]
Hi @schwa1z,

this is a Verilator warning that is by default promoted to an error. Verilator assumes that an 8k bit replication is wrong, but for large vector sizes it is perfectly normal to encounter such replication counts. Therefore, it should be safe to ignore that warning, which you can do by adding the `-Wno-WIDTHCONCAT` option to Verilator's invocation in the [simulation Makefile](https://github.com/vproc/vicuna/blob/main/sim/Makefile). E.g., adding that option to line 107 after the other options that silence various warnings should resolve this problem:

https://github.com/vproc/vicuna/blob/bda35112a983e9adb4ea8413b0afc2f0d91e7563/sim/Makefile#L107

**Comment by schwa1z** [comment]
Thanks! It's clear!
