### ISSUE TITLE
Updates for newer verilator

### ISSUE THREAD

**Issue by stevobailey** [vproc/vicuna#11]
Which version of verilator are you using? With 4.210, I need to make a couple of changes to verilator_main.cpp for it to work. First, I include the following:
```
#include "Vvproc_top___024root.h"
```

I also have to change the following line:
https://github.com/vproc/vicuna/blob/beb86f900f8957587fcacd6525c8815e0fbd0c41/sim/verilator_main.cpp#L239

to become (adds rootp in the hierarchy):
```
top->rst_ni, top->mem_req_o, top->mem_addr_o, top->rootp->vproc_top__DOT__v_core__DOT__vreg_rd_hazard_map_q, top->rootp->vproc_top__DOT__v_core__DOT__vreg_wr_hazard_map_q, 0);
```

**Comment by michael-platzer** [comment]
I am using Verilator 4.200. Thanks for looking into this and providing a fix, I am working on a patch that adapts this line depending to the version of Verilator.
