### ISSUE TITLE
Misc. error

### ISSUE THREAD

**Issue by stevobailey** [vproc/vicuna#49]
Not sure what the exact error is, but see #47 for a new test case that fails. The provided assembly passes when VREG_W is 128, but not when it is larger. Can you first confirm that it is a bug?

**Comment by michael-platzer** [comment]
Thanks @stevobailey for the new test case! I managed to track it down and can confirm it is a bug indeed (one of those hard to find bugs that only manifest themselves under certain conditions). Fortunately, the fix is straightforward.
