### ISSUE TITLE
riscv-gnu-toolchain dropped the rvv-intrinsic branch

### ISSUE THREAD

**Issue by cklarhorst** [vproc/vicuna#64]
Hi,

I just noted that the riscv-gnu-toolchain git doesn't have the rvv-intrinsic branch anymore.
Is the rvv-next branch equally suitable, or is it better to stay on the current master branch?

Cheers,
Christian.

**Comment by michael-platzer** [comment]
Hi @cklarhorst,

Thanks for the heads-up, it appears that the vector code generation has been merged into the master branch, now that the V extension has been ratified. I do not know what the rvv-next branch is about, but I have updated Vicuna's README and the CI script to build the toolchain from the master branch. CI is currently rebuilding the toolchain, so hopefully that did not break anything :crossed_fingers:
