### ISSUE TITLE
Signal stability issue on result interface

### ISSUE THREAD

**Issue by moimfeld** [vproc/vicuna#94]
Hi @michael-platzer 

## Issue
There is an issue regarding signal stability for result transactions. If a core cannot accept the result immediately, it sometimes happens that Vicuna changes the content of the result transactions (id, exccode, rd, we ...). This is not allowed by the x-interface as the signals must remain stable until the result transaction completed. Below you can see an exemplary screenshot of what can happen:

![issue_94](https://user-images.githubusercontent.com/73966745/179518282-4513014d-a140-41a6-9a61-2ecd207edd7f.png)

I have not further investigated the issue but from what I've seen the issue only arises if multiple instructions have pending result transactions.

## How to reproduce

To reproduce this issue you can run the `cvxif_test_direct_issue_94` test in the UVM environment.

**Comment by moimfeld** [comment]
Hi @michael-platzer 

Thank you very much for the fix! 😄

Still, I will keep the issue open until the discussion in the cvxif issue you opened comes to a conclusion.

**Comment by michael-platzer** [comment]
Hi @moimfeld, with commit 40a11a2 this should now be definitely resolved. XIF result signals should now hopefully remain stable during a transaction :)

**Comment by moimfeld** [comment]
Hi @michael-platzer,

I will close this issue then. Thanks again!
